# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HSCSITO_ASG
                                 A QGIS plugin
 Tratamiento de observaciones convencionales de Estaciones Totales en QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-12
        copyright            : (C) 2024 by Alexandra Giseth Flor Avilez, Juan Esteban Guzmán Martínez
        email                : alexandraavilez267@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HSCSITO_ASG
                                 A QGIS plugin
 Tratamiento de observaciones convencionales de Estaciones Totales en QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-12
        copyright            : (C) 2024 by Alexandra Giseth Flor Avilez, Juan Esteban Guzmán Martínez
        email                : alexandraavilez267@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HSCSITO_ASG class from file HSCSITO_ASG.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .HSCSITO_ASG import HSCSITO_ASG
    return HSCSITO_ASG(iface)
    








