# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HSCSITO_ASGDialog
                                 A QGIS plugin
 Tratamiento de observaciones convencionales de Estaciones Totales en QGIS.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-12
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Alexandra Giseth Flor Avilez, Juan Esteban Guzmán Martínez
        email                : alexandraavilez267@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'HSCSITO_ASG_dialog_base.ui'))

FORM_CLASS_2, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'fbk_a_coordenadas_vent.ui'))

FORM_CLASS_3, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'fbk_a_starnet_vent.ui'))

FORM_CLASS_4, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'fbk_a_geosuite_vent.ui'))

class HSCSITO_ASGDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(HSCSITO_ASGDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

class HSCSITO_ASGDialog_2(QtWidgets.QDialog, FORM_CLASS_2):
    def __init__(self, parent=None):
        """Constructor."""
        super(HSCSITO_ASGDialog_2, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

class HSCSITO_ASGDialog_3(QtWidgets.QDialog, FORM_CLASS_3):
    def __init__(self, parent=None):
        """Constructor."""
        super(HSCSITO_ASGDialog_3, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

class HSCSITO_ASGDialog_4(QtWidgets.QDialog, FORM_CLASS_4):
    def __init__(self, parent=None):
        """Constructor."""
        super(HSCSITO_ASGDialog_4, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)